### ISSUE TITLE
SparseLayers.recallToGrid setting incorrect X position

### ISSUE THREAD

**Issue by rygaar72** [yellowstonegames/SquidLib#213]
https://github.com/yellowstonegames/SquidLib/blob/266920dafcf6dfa3ad40b66f0fa58fd75e9d385a/squidlib/src/main/java/squidpony/squidgrid/gui/gdx/SparseLayers.java#L1986

Refer to code - simple typo, using `glyph.getY()` where `glyph.getX()` should be used in the recallToGrid methods.

**Comment by tommyettinger** [comment]
Nice catch! I'll get on this now, sorry for the delay.
